name: responsive_scaffold
description: On mobile it shows a list and pushes to details and on tablet it shows the List and the selected item.
version: 1.3.0+2
homepage: https://github.com/fluttercommunity/responsive_scaffold
maintainer: Rody Davis (@rodydavis)

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
